---
title: "Organizing"
author: "Group 10"
date: "`r Sys.Date()`"
output: word_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```


Uploading csv's 

```{r }
r <- read.csv("r_so_traffic.csv")

r$cat <- 'R'

p <- read.csv("py_so_traffic.csv")

p$cat <- 'P'

full <- rbind(r,p)

summary(full)

```

####

```{r pressure, echo=FALSE}
hist(full$question_count)

```

```{r}

library(fpp3)

r$date <- as.Date(with(r, paste(year, month, day,sep="-")), "%Y-%m-%d")
#r$date
r$date <- yearmonth(r$date)

p$date <- as.Date(with(p, paste(year, month, day,sep="-")), "%Y-%m-%d")
#p$date
p$date <- yearmonth(p$date)



```

```{r}
rqc <- aggregate(question_count ~ date, r, sum)
rqc

```


```{r}
pqc <- aggregate(question_count ~ date, p, sum)
pqc
```


```{r}

full_agg <- merge(rqc, pqc, by = "date")

colnames(full_agg) <- c('date', 'r_question_count','py_question_count' )


full_agg$total <- full_agg$r_question_count + full_agg$py_question_count

full_agg


```
```{r}
full_agg[is.na(full_agg)] = 0
hist(full_agg$r_question_count)
```
```{r}
hist(full_agg$py_question_count)
```

```{r}
hist(full_agg$total)
```
```{r}
full_agg <- tsibble(full_agg)

autoplot(full_agg, .vars = total)

```
```{r}

full_agg <- 
  full_agg %>% tsibble::fill_gaps() 

drift_model <- full_agg %>% 
  model(
    NAIVE(total ~ drift())
  )
  
drift_model %>% 
  forecast(h=12) %>%
  autoplot(full_agg)

accuracy(drift_model)
  
```
```{r}
fit <- full_agg %>%
  model(NAIVE(total))

fit %>%
  forecast(h="1 years") %>%
  autoplot(full_agg)

accuracy(fit)

fit2 <- full_agg %>%
  model(SNAIVE(total))

fit2 %>%
  forecast(h="1 years") %>%
  autoplot(full_agg)

accuracy(fit2)

```

```{r}
fit %>%
  forecast(h="1 years") %>%
  view()

fit2 %>%
  forecast(h="1 years") %>%
  view()
```


```{r}
arima_fit <- full_agg %>%
  model(
    arima_auto = ARIMA(total), # (0,1,0)(1,0,0)
    arima2 = ARIMA(total ~ pdq(0, 1, 0) + PDQ(1,1,1)), 
    arima3 = ARIMA(total ~pdq(0, 1, 0) + PDQ(1,1,2)), 
    arima4 =  ARIMA(total ~pdq(0, 1, 0) + PDQ(0,1,0)), 
    arima5 =  ARIMA(total ~pdq(0, 1, 0) + PDQ(0,1,1)), 
    arima6 =  ARIMA(total ~pdq(1, 1, 0) + PDQ(0,1,2)), 
    arima7 =  ARIMA(total ~pdq(2, 0, 2) + PDQ(1,1,1)), 
    arima8 = ARIMA(box_cox(total, lambda=0.5) ~pdq(2, 0, 2) + PDQ(1,1,1)), 
    arima9 = ARIMA(box_cox(total, lambda=0.4) ~ pdq(2, 0, 2) + PDQ(1,1,1)),
    
    ) 

accuracy(arima_fit)
report(arima_fit)

```
```{r}
arima_fit2 <- full_agg %>%
  model(ARIMA(box_cox(total, lambda=0.4) ~pdq(2, 0, 2) + PDQ(1,1,1)))

arima_fit2 %>% 
  forecast(h="2 year") %>% 
  autoplot(full_agg)

arima_fit2 %>% gg_tsresiduals()

#arima_fit2 %>%
  #forecast(h="1 year") 
```

